apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      env: prod
      bu: cis
  template:
    metadata:
      labels:
        app: nginx
        env: prod
        bu: cis
        criticality: p1
      name: mypod
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80